name: Solar Radiation Measurement

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
        pip install jupyter

    - name: Debug:List all files in repo
      run: |
        ls -R

    - name: Debug:List installed Python packages
      run: pip list

    - name: Run Jupyter Notebook tests
      run: |
        jupyter nbconvert --to script scripts/jup.ipynb
        python scripts/jup.py || exit 1

    - name: Run Streamlit app (optional)
      run: |
        streamlit run scripts/app.py --server.headless true
      env:
        STREAMLIT_SERVER_HEADLESS: 'true'
